{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f55ef886-f370-4759-824b-54188446814d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import json\n",
    "from itertools import product\n",
    "\n",
    "ORDER_SIZE = 5000\n",
    "CHUNK = 100\n",
    "\n",
    "# Data structure for allocator\n",
    "def create_venue_list(snapshot):\n",
    "    venues = []\n",
    "    for venue, row in snapshot.iterrows():\n",
    "        venues.append({\n",
    "            'venue': venue,\n",
    "            'ask': row['ask_px_00'],\n",
    "            'ask_size': row['ask_sz_00'],\n",
    "            'fee': 0.0,\n",
    "            'rebate': 0.0\n",
    "        })\n",
    "    return venues\n",
    "\n",
    "def compute_cost(split, venues, order_size, lambda_over, lambda_under, theta_queue):\n",
    "    executed = 0\n",
    "    cash_spent = 0\n",
    "    for i in range(len(venues)):\n",
    "        exe = min(split[i], venues[i]['ask_size'])\n",
    "        executed += exe\n",
    "        cash_spent += exe * (venues[i]['ask'] + venues[i]['fee'])\n",
    "        maker_rebate = max(split[i] - exe, 0) * venues[i]['rebate']\n",
    "        cash_spent -= maker_rebate\n",
    "\n",
    "    underfill = max(order_size - executed, 0)\n",
    "    overfill = max(executed - order_size, 0)\n",
    "    risk_penalty = theta_queue * (underfill + overfill)\n",
    "    cost_penalty = lambda_under * underfill + lambda_over * overfill\n",
    "    return cash_spent + risk_penalty + cost_penalty\n",
    "\n",
    "def allocator(snapshot, lambda_over, lambda_under, theta_queue, remaining_qty):\n",
    "    venues = create_venue_list(snapshot)\n",
    "    splits = [[]]\n",
    "    for v in range(len(venues)):\n",
    "        new_splits = []\n",
    "        for alloc in splits:\n",
    "            used = sum(alloc)\n",
    "            max_v = min(remaining_qty - used, venues[v]['ask_size'])\n",
    "            for q in range(0, int(max_v) + 1, CHUNK):\n",
    "                new_splits.append(alloc + [q])\n",
    "        splits = new_splits\n",
    "\n",
    "    best_cost = float('inf')\n",
    "    best_split = [0] * len(venues)\n",
    "    for alloc in splits:\n",
    "        if sum(alloc) != remaining_qty:\n",
    "            continue\n",
    "        cost = compute_cost(alloc, venues, remaining_qty, lambda_over, lambda_under, theta_queue)\n",
    "        if cost < best_cost:\n",
    "            best_cost = cost\n",
    "            best_split = alloc\n",
    "    return {venue['venue']: qty for venue, qty in zip(venues, best_split)}\n",
    "\n",
    "def run_backtest(df, strategy_func, params=None):\n",
    "    total_cost = 0\n",
    "    total_shares = 0\n",
    "    remaining_qty = ORDER_SIZE\n",
    "\n",
    "    for ts in df['ts_event'].unique():\n",
    "        if remaining_qty <= 0:\n",
    "            break\n",
    "        snapshot = df[df['ts_event'] == ts].set_index('publisher_id')\n",
    "        market_data = {\n",
    "            venue: {'ask_px': row['ask_px_00'], 'ask_sz': row['ask_sz_00']}\n",
    "            for venue, row in snapshot.iterrows()\n",
    "        }\n",
    "\n",
    "        if params:\n",
    "            allocations = strategy_func(snapshot, *params, remaining_qty)\n",
    "        else:\n",
    "            allocations = strategy_func(market_data, remaining_qty)\n",
    "\n",
    "        for venue, shares in allocations.items():\n",
    "            px = market_data[venue]['ask_px']\n",
    "            sz = market_data[venue]['ask_sz']\n",
    "            executed = min(shares, sz, remaining_qty)\n",
    "            if executed > 0:\n",
    "                total_cost += executed * px\n",
    "                total_shares += executed\n",
    "                remaining_qty -= executed\n",
    "\n",
    "    avg_price = total_cost / total_shares if total_shares > 0 else 0\n",
    "    return total_cost, avg_price\n",
    "\n",
    "def best_ask_strategy(market_data, remaining_qty):\n",
    "    sorted_venues = sorted(market_data.items(), key=lambda x: x[1]['ask_px'])\n",
    "    allocations = {venue: 0 for venue, _ in sorted_venues}\n",
    "    qty_left = remaining_qty\n",
    "    for venue, data in sorted_venues:\n",
    "        if qty_left <= 0:\n",
    "            break\n",
    "        executable = min(qty_left, data['ask_sz'])\n",
    "        allocations[venue] = executable\n",
    "        qty_left -= executable\n",
    "    return allocations\n",
    "\n",
    "def twap_strategy(df):\n",
    "    times = sorted(df['ts_event'].unique())\n",
    "    total_cost = 0\n",
    "    total_shares = 0\n",
    "    remaining_qty = ORDER_SIZE\n",
    "    bucket_size = ORDER_SIZE // len(times)\n",
    "\n",
    "    for ts in times:\n",
    "        if remaining_qty <= 0:\n",
    "            break\n",
    "        snapshot = df[df['ts_event'] == ts].set_index('publisher_id')\n",
    "        market_data = {\n",
    "            venue: {'ask_px': row['ask_px_00'], 'ask_sz': row['ask_sz_00']}\n",
    "            for venue, row in snapshot.iterrows()\n",
    "        }\n",
    "        allocations = best_ask_strategy(market_data, min(bucket_size, remaining_qty))\n",
    "        for venue, shares in allocations.items():\n",
    "            px = market_data[venue]['ask_px']\n",
    "            sz = market_data[venue]['ask_sz']\n",
    "            executed = min(shares, sz, remaining_qty)\n",
    "            if executed > 0:\n",
    "                total_cost += executed * px\n",
    "                total_shares += executed\n",
    "                remaining_qty -= executed\n",
    "\n",
    "    avg_price = total_cost / total_shares if total_shares > 0 else 0\n",
    "    return total_cost, avg_price\n",
    "\n",
    "def vwap_strategy(df):\n",
    "    total_volume = df['ask_sz_00'].sum()\n",
    "    total_cost = 0\n",
    "    total_shares = 0\n",
    "    remaining_qty = ORDER_SIZE\n",
    "\n",
    "    for ts in df['ts_event'].unique():\n",
    "        if remaining_qty <= 0:\n",
    "            break\n",
    "        snapshot = df[df['ts_event'] == ts].set_index('publisher_id')\n",
    "        vol = snapshot['ask_sz_00'].sum()\n",
    "        target = (vol / total_volume) * ORDER_SIZE\n",
    "        market_data = {\n",
    "            venue: {'ask_px': row['ask_px_00'], 'ask_sz': row['ask_sz_00']}\n",
    "            for venue, row in snapshot.iterrows()\n",
    "        }\n",
    "        allocations = best_ask_strategy(market_data, min(target, remaining_qty))\n",
    "        for venue, shares in allocations.items():\n",
    "            px = market_data[venue]['ask_px']\n",
    "            sz = market_data[venue]['ask_sz']\n",
    "            executed = min(shares, sz, remaining_qty)\n",
    "            if executed > 0:\n",
    "                total_cost += executed * px\n",
    "                total_shares += executed\n",
    "                remaining_qty -= executed\n",
    "\n",
    "    avg_price = total_cost / total_shares if total_shares > 0 else 0\n",
    "    return total_cost, avg_price\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1b6abfb8-ad67-4721-97d7-9513fae36ac7",
   "metadata": {},
   "outputs": [],
   "source": [
    "def main():\n",
    "    df = pd.read_csv('l1_day.csv')\n",
    "    df['ts_event'] = pd.to_datetime(df['ts_event'])\n",
    "    df = df.sort_values(['ts_event', 'publisher_id'])\n",
    "    df = df.groupby(['ts_event', 'publisher_id']).first().reset_index()\n",
    "\n",
    "    param_grid = list(product([0.1, 1, 10], repeat=3))\n",
    "    best_result = {'cost': float('inf'), 'params': None, 'avg_price': 0}\n",
    "\n",
    "    for lambda_over, lambda_under, theta_queue in param_grid:\n",
    "        cost, price = run_backtest(df, allocator, (lambda_over, lambda_under, theta_queue))\n",
    "        if price > 0 and cost < best_result['cost']:\n",
    "            best_result = {'cost': cost, 'params': {\n",
    "                'lambda_over': lambda_over,\n",
    "                'lambda_under': lambda_under,\n",
    "                'theta_queue': theta_queue\n",
    "            }, 'avg_price': price}\n",
    "\n",
    "    best_ask_cost, best_ask_price = run_backtest(df, best_ask_strategy)\n",
    "    twap_cost, twap_price = twap_strategy(df)\n",
    "    vwap_cost, vwap_price = vwap_strategy(df)\n",
    "\n",
    "    savings = {\n",
    "        'best_ask': ((best_ask_price - best_result['avg_price']) / best_result['avg_price']) * 10000,\n",
    "        'twap': ((twap_price - best_result['avg_price']) / best_result['avg_price']) * 10000,\n",
    "        'vwap': ((vwap_price - best_result['avg_price']) / best_result['avg_price']) * 10000\n",
    "    }\n",
    "\n",
    "    output = {\n",
    "        'tuned': {\n",
    "            'parameters': best_result['params'],\n",
    "            'total_cost': best_result['cost'],\n",
    "            'average_price': best_result['avg_price']\n",
    "        },\n",
    "        'best_ask': {\n",
    "            'total_cost': best_ask_cost,\n",
    "            'average_price': best_ask_price\n",
    "        },\n",
    "        'twap': {\n",
    "            'total_cost': twap_cost,\n",
    "            'average_price': twap_price\n",
    "        },\n",
    "        'vwap': {\n",
    "            'total_cost': vwap_cost,\n",
    "            'average_price': vwap_price\n",
    "        },\n",
    "        'savings_vs_baseline_bps': savings\n",
    "    }\n",
    "\n",
    "    print(json.dumps(output, indent=2))\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fa7ae5fa-9166-4098-8aaa-f63b3176faf3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "281f7fc6-8201-4ed5-8434-ff7c075bd6c3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
